<?php
/**
Package		: MUSCS
Lib.Info	: API token generator when a user registering
		: API token generated by converting IP Address,Date and Time to SHA-1, so in the future the user could use
			the API token to integrate their apps to MUSCS (when API enable = true)
			The token could also used as Session validation.
Link		: http://www.wisebearproject.com
Author		: Juki Gladak <jukigladak@gmail.com>
Copyright	: Copyright (c) 2018 Juki Gladak <jukigladak@gmail.com>
license		: GNU General Public License 3
*/

# Function to generate client API token
function get_api() {
    //Get the client IP address from all possible ways
	$ipaddress = '';
    if ($_SERVER['HTTP_CLIENT_IP'])
        $ipaddress = $_SERVER['HTTP_CLIENT_IP'];
    else if($_SERVER['HTTP_X_FORWARDED_FOR'])
        $ipaddress = $_SERVER['HTTP_X_FORWARDED_FOR'];
    else if($_SERVER['HTTP_X_FORWARDED'])
        $ipaddress = $_SERVER['HTTP_X_FORWARDED'];
    else if($_SERVER['HTTP_FORWARDED_FOR'])
        $ipaddress = $_SERVER['HTTP_FORWARDED_FOR'];
    else if($_SERVER['HTTP_FORWARDED'])
        $ipaddress = $_SERVER['HTTP_FORWARDED'];
    else if($_SERVER['REMOTE_ADDR'])
        $ipaddress = $_SERVER['REMOTE_ADDR'];
    else
        $ipaddress = 'UNKNOWN';
	
	//Get current date and time in a single un-spaced string
	$curDateTime = date("Ymdhis");
	
	//Concatenate DateTime and IP Address
	$rawToken = $curDateTime.$ipaddress;
	
	//Generate API in SHA-1
	$apiToken = sha1($rawToken);
	return $apiToken;
}

# Get the API Token
$clientApi = get_api();
echo $clientApi;

?>
